### ISSUE TITLE
Function in controller

### ISSUE THREAD

**Issue by miquelangeld** [eventhomes/laravel-mandrillhooks#11]
Hello.

you say in the step two:

add this route:
post('mandrill-webhook', ['as' => 'mandrill.webhook', 'uses' => 'MandrillController@handleWebHook']);

But in the controller the function handleWebHook doesn't exists. 

Thanks in advance.

**Comment by miquelangeld** [comment]
Ok, the function is in EventHomes\Api\Webhooks\MandrillWebhookController; but for some reason Laravel can't find it.

**Comment by lostincode** [comment]
Hello,

So sorry for the late reply. I hope you got it sorted. You will need to import that controller for Laravel to find it. Feel free to reply if I can be of further assistance.
