### ISSUE TITLE
Signature will never match the header

### ISSUE THREAD

**Issue by tiagoraposeira** [eventhomes/laravel-mandrillhooks#8]
$request->all() on validateSignature will not work, only got it to work using the $_POST variable.
I think this is due to the way Laravel retrieves the request array. Can you guys have a look at it?

**Comment by jbrooksuk** [comment]
Out of interest, why do you suspect that `$request->all()` won't work?

**Comment by tiagoraposeira** [comment]
I'm not on the project that was using that package anymore, so I cannot give you a full insight right now. But as I've said, I think that the laravel request array does not output the exact same thing as the native $_POST variable, thus falling when validating the signature.

**Comment by lostincode** [comment]
If anyone comes across this issue, feel free to open an issue with example. I am unable to reproduce.

**Comment by MattApril** [comment]
This is valid issue. it should be $request->input() (for Laravel 5 for sure)

**Comment by lostincode** [comment]
> This is valid issue. it should be $request->input() (for Laravel 5 for sure)

@MattApril PRs welcome
